import { Router } from 'express';
import { aiController } from '../controllers/ai.controller.js';
import { validateBody } from '../middleware/validate.js';
import { generateSchema, refineSchema, settingsSchema } from '../middleware/schemas.js';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { aiRateLimiter } from '../middleware/rateLimiters.js';
import { asyncHandler } from '../middleware/asyncHandler.js';

const router = Router();

/**
 * GET /api/v1/ai/schema
 * Returns the dynamic list of job description sections generated by the backend.
 */
router.get('/schema', asyncHandler(aiController.getSchema));

/**
 * GET /api/v1/ai/providers
 * Returns the list of all configured LLM providers and their supported models.
 */
router.get('/providers', asyncHandler(aiController.getProviders));

/**
 * GET /api/v1/ai/settings
 * Retrieves active provider, model, and target language configurations.
 */
router.get('/settings', asyncHandler(aiController.getSettings));

/**
 * PUT /api/v1/ai/settings
 * Updates active provider, model, and target language configurations in the database.
 */
router.put('/settings', validateBody(settingsSchema), asyncHandler(aiController.updateSettings));

/**
 * POST /api/v1/ai/generate
 * Streams a dynamically built JSON job description using backend schema and settings.
 */
router.post('/generate', aiRateLimiter, authMiddleware, validateBody(generateSchema), asyncHandler(aiController.generate));

/**
 * POST /api/v1/ai/refine-section
 * Refines specific sections using settings configurations.
 */
router.post('/refine-section', aiRateLimiter, validateBody(refineSchema), asyncHandler(aiController.refineSection));

export default router;
