import { Router, Request, Response, NextFunction } from 'express';
import { OpenRouterLLMProvider } from '../services/llm.service.js';
import { configService } from '../services/config.service.js';
import { PROVIDERS_CONFIG, LLMProviderType } from '../types/llm.js';
import { prisma } from '../config/db.js';
import { validateBody } from '../middleware/validate.js';
import { generateSchema, refineSchema, settingsSchema } from '../middleware/schemas.js';
import { authMiddleware } from '../middleware/auth.middleware.js';
import rateLimit from 'express-rate-limit';

const router = Router();
const llmProvider = new OpenRouterLLMProvider();

const aiRateLimiter = rateLimit({
  windowMs: 60 * 1000, // 1 minute
  max: 5, // Limit each IP to 5 requests per minute
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many requests from this IP, please try again after a minute.' }
});

/**
 * GET /api/v1/ai/schema
 * Returns the dynamic list of job description sections generated by the backend.
 */
router.get('/schema', (req: Request, res: Response, next: NextFunction) => {
  try {
    const schema = configService.getSectionsSchema();
    res.json({ schema });
  } catch (error: any) {
    next(error);
  }
});

/**
 * GET /api/v1/ai/providers
 * Returns the list of all configured LLM providers and their supported models.
 */
router.get('/providers', (req: Request, res: Response, next: NextFunction) => {
  try {
    res.json({ providers: Object.values(PROVIDERS_CONFIG) });
  } catch (error: any) {
    next(error);
  }
});

/**
 * GET /api/v1/ai/settings
 * Retrieves active provider, model, and target language configurations.
 */
router.get('/settings', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const settings = await configService.getActiveSettings();
    res.json(settings);
  } catch (error: any) {
    next(error);
  }
});

/**
 * PUT /api/v1/ai/settings
 * Updates active provider, model, and target language configurations in the database.
 * Validates the inputs through settingsSchema middleware.
 */
router.put('/settings', validateBody(settingsSchema), async (req: Request, res: Response, next: NextFunction) => {
  const { provider, model, language } = req.body;

  try {
    await configService.updateActiveSettings(
      provider as LLMProviderType,
      model,
      language as 'en' | 'fr' | 'ar'
    );
    res.json({ message: 'AI settings updated successfully', settings: { provider, model, language } });
  } catch (error: any) {
    next(error);
  }
});

/**
 * POST /api/v1/ai/generate
 * Streams a dynamically built JSON job description using backend schema and settings.
 * Validates the inputs through generateSchema middleware.
 */
router.post('/generate', aiRateLimiter, authMiddleware, validateBody(generateSchema), async (req: Request, res: Response) => {
  const { prompt, seniority, location, workType, employmentType, tone } = req.body;

  const abortController = new AbortController();
  req.on('close', () => {
    console.log('🔌 Client connection closed. Aborting LLM request.');
    abortController.abort();
  });

  try {
    // 1. Fetch active AI configs & dynamic schema
    const settings = await configService.getActiveSettings();
    const sectionsSchema = configService.getSectionsSchema();
    
    // Set up SSE headers
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no');

    // Send initial configuration details
    res.write(`data: ${JSON.stringify({ 
      status: 'started', 
      provider: settings.provider, 
      model: settings.model,
      language: settings.language 
    })}\n\n`);

    let responseBody = '';
    
    await llmProvider.generateStream(
      settings.provider,
      settings.model,
      {
        prompt,
        seniority,
        location,
        workType,
        employmentType,
        tone
      },
      settings.language,
      sectionsSchema,
      (chunk) => {
        responseBody += chunk;
        res.write(`data: ${JSON.stringify({ chunk })}\n\n`);
      },
      abortController.signal
    );

    // Asynchronously log usage metrics
    prisma.usageStat.create({
      data: {
        action: 'generate_full',
        tokensUsed: Math.round(responseBody.length / 4)
      }
    }).catch(err => console.error('Failed to log usage stat:', err));

    res.write(`data: ${JSON.stringify({ status: 'completed' })}\n\n`);
    res.end();
  } catch (error: any) {
    if (abortController.signal.aborted) {
      console.log('Generation request successfully aborted.');
      res.end();
      return;
    }
    console.error('Generation router error:', error);
    res.write(`data: ${JSON.stringify({ error: error.message || 'AI generation failed' })}\n\n`);
    res.end();
  }
});

/**
 * POST /api/v1/ai/refine-section
 * Refines specific sections using settings configurations.
 * Validates the inputs through refineSchema middleware.
 */
router.post('/refine-section', aiRateLimiter, validateBody(refineSchema), async (req: Request, res: Response, next: NextFunction) => {
  const { sectionName, currentContent, action } = req.body;

  try {
    const settings = await configService.getActiveSettings();

    const refinedContent = await llmProvider.refine(
      settings.provider,
      settings.model,
      {
        sectionName,
        currentContent,
        action
      },
      settings.language
    );

    prisma.usageStat.create({
      data: {
        action: `refine_${action}`,
        tokensUsed: Math.round((currentContent.length + refinedContent.length) / 4)
      }
    }).catch(err => console.error('Failed to log usage stat:', err));

    res.json({ refinedContent });
  } catch (error: any) {
    next(error);
  }
});

export default router;
